[package]
edition      = "2021"
name         = "watch-rs"
version      = "0.1.0"

[[bin]]
name = "watch-rs"
version = "./src/bin/main.rs"
test = false

[[test]]
harness = false
name    = "hello_test"

[lib]
test = false

[dependencies]
embassy-executor = {version= "0.9.1", features= ["defmt", "executor-thread"]}
critical-section = "1"
esp-alloc = { version = "*" , features= ["defmt"]}
esp-backtrace = { version = "*", features = [
    "panic-handler",
    "defmt",
  "esp32s3",
] }
esp-bootloader-esp-idf = { version = "*", features=["esp32s3"]}
esp-hal = { version = "*", features = ["defmt", "unstable", "esp32s3"] }
esp-rtos = { version = "*", features = ["esp-radio", "defmt", "embassy", "esp32s3"] }
esp-radio = { version= "0.17.0", features = [
    "sniffer",
    "unstable",
    "wifi",
  "esp32s3",
  "defmt",
] }
ieee80211 = { version = "0.5.9", default-features = false }
embedded-graphics = "0.8.2"
panic-rtt-target = "0.2.0"
mipidsi = "0.10.0"
embedded-hal-bus = "0.3.0"
pcf85063a = "0.1.1"
defmt = "1.0.1"
rtt-target = {version= "0.6.2", features= ["defmt"]}
sntpc-net-embassy = { version= "0.8.0", default-features=false, features= ["defmt"]}
sntpc= {version="0.8.1", default-features= false, features= ["defmt"]}
static_cell = "2.1.1"
embassy-net = {version= "0.8.0", features = ["defmt", "udp", "dns", "medium-ethernet", "dhcpv4"]}
embassy-time = "0.5.0"
heapless = {version= "0.9.2", default-features= false}
jiff = {version= "0.2.10", default-features= false, features= ["static", ]}
time = { version= "0.3.47", default-features= false, features= ["alloc"]}
[profile.dev]
# Rust debug is too slow.
# For debug builds always builds with some optimization
opt-level = 3

[profile.release]
codegen-units    = 1     # LLVM can perform better optimizations using a single thread
debug            = 2
debug-assertions = false
incremental      = false
lto              = 'fat'
opt-level        = 's'
overflow-checks  = false
